Repository yunionio/yunionos, pull requests merged in 2019-11, with the labels that each got.

#6 fix: rpm missing isolinux.bin
  bin/makerpm
Labels: approved, lgtm, size/XS

#7 bugfix: mkdir dropbear temp path
  baremetal_prepare/prepare.sh
Labels: size/XS

#8 optimize: add query status
  baremetal_prepare/prepare.sh
Labels: approved, lgtm
